name: SFTP Deploy to cPanel

on:
  push:
    branches: [ main ]   # Change to your main branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: "./"               # Upload everything from repo root
          remote_path: ${{ secrets.SFTP_TARGET }}
          sftp_only: true                # Use SFTP only
