name: FTP Deploy to cPanel

on:
  push:
    branches: [ main ]  # Change to your default branch if not 'main'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./          # Root of your repo, adjust if needed
          server-dir: ${{ secrets.FTP_TARGET }}
